#      ___           ___           ___           ___     
#     /\  \         /\__\         /\__\         |\__\    
#     \:\  \       /::|  |       /:/  /         |:|  |   
#      \:\  \     /:|:|  |      /:/  /          |:|  |   
#      /::\  \   /:/|:|__|__   /:/  /  ___      |:|__|__ 
#     /:/\:\__\ /:/ |::::\__\ /:/__/  /\__\ ____/::::\__\
#    /:/  \/__/ \/__/~~/:/  / \:\  \ /:/  / \::::/~~/~   
#   /:/  /            /:/  /   \:\  /:/  /   ~~|:|~~|    
#   \/__/            /:/  /     \:\/:/  /      |:|  |    
#                   /:/  /       \::/  /       |:|  |    
#                   \/__/         \/__/         \|__|    

# updated 07/11/22
set-option -g default-shell /bin/zsh
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# Allows cmd + k to clear window
bind -n C-k clear-history

# Plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @catppuccin_flavour 'mocha'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
